---
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12.3
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: PYTHONPATH=. python -m unittest tests.test_app
  build:
    docker:
      - image: cimg/base:2024.05
    resource_class: medium
    environment:
      TAG: 0.<< pipeline.number >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_HUB_USER/$CIRCLE_PROJECT_REPONAME:$TAG --push .
            docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_HUB_USER/$CIRCLE_PROJECT_REPONAME --push .
  deploy:
    docker:
      - image: cimg/base:2024.05
    resource_class: small
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER "
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS &&
            docker container stop $CIRCLE_PROJECT_REPONAME || true &&
            docker container rm $CIRCLE_PROJECT_REPONAME || true &&
            docker pull $DOCKER_HUB_USER/$CIRCLE_PROJECT_REPONAME &&
            docker run --name $CIRCLE_PROJECT_REPONAME -p 80:5000 -d $DOCKER_HUB_USER/$CIRCLE_PROJECT_REPONAME"
workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build