---
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12.3
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run tests
          command: PYTHONPATH=. python -m unittest tests.test_main
  build:
    docker:
      - image: cimg/base:2024.05
    resource_class: medium
    environment:
      TAG: 0.<< pipeline.number >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:$TAG --push .
            docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME --push .

workflows:
  run_tests:
    jobs:
      - test
      - build:
          requires:
            - test