---
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9.9
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run tests
          command: PYTHONPATH=. python -m unittest tests.test_main

workflows:
  run_tests:
    jobs:
      - test